### ISSUE TITLE
Probable languages not working

### ISSUE THREAD

**Issue by guilherme-p** [yoeo/guesslang#1]
Using the guesslang library I can't get the desired output, which would be ['C', 'Python']
Instead, I only get ['C']

```
from guesslang import Guess

with open('glang_test', 'r') as myfile:
  data = myfile.read()

langs = Guess().probable_languages(data)

print(data, type(data))
print(langs)
```

```
from __future__ import print_function


def dump_code(code):
  print(code)


if __name__ == "__main__":
    dump_code("""
        #include<stdio.h>

        int main(int argc, char** argv)
        {
          char* command = argv[0];
          printf("%s - %d args\n", command, --argc);
          return 0;
        }
    """
    )

```

**Comment by yoeo** [comment]
Hello @guilherme-p  thank you for your comment.

As you noted, the `probable_languages` method didn't work well, I pushed a better version of it in this commit https://github.com/yoeo/guesslang/commit/52e8f3e39ea015de217f6f89b10823e7d8dfba48

One limitation the `probable_languages` feature is that: the machine learning model used here is trained to detect only one language per input, trying to detect multiple languages with the same model may sometimes give funny results.
