### ISSUE TITLE
Uninstallable due to outdated tensorflow specification

### ISSUE THREAD

**Issue by AndydeCleyre** [yoeo/guesslang#12]
```bash
pip install guesslang
```

```
Collecting guesslang
  Using cached https://files.pythonhosted.org/packages/d5/e2/0416000ea8c42665ca1c3a9b527b585e9a9610b4a6494d728358f25a3a46/guesslang-0.9.3-py3-none-any.whl
Collecting numpy (from guesslang)
  Using cached https://files.pythonhosted.org/packages/91/e7/6c780e612d245cca62bc3ba8e263038f7c144a96a54f877f3714a0e8427e/numpy-1.16.2-cp37-cp37m-manylinux1_x86_64.whl
Collecting tensorflow==1.7.0rc1 (from guesslang)
  Could not find a version that satisfies the requirement tensorflow==1.7.0rc1 (from guesslang) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1)
No matching distribution found for tensorflow==1.7.0rc1 (from guesslang)
```

pip 19.0.3

**Comment by yoeo** [comment]
Thanks for the warning @AndydeCleyre

**Comment by ViktorBarzin** [comment]
I can confirm the bug affects me as well. I'm running Fedora 29 with python3.7

**Comment by Vikas2426** [comment]
> I can confirm the bug affects me as well. I'm running Fedora 29 with python3.7
> 
> EDIT:
> problem cna be partially overcome by cloning the repo and replacing the `tensorflow==..` with just `tensorflow`. This installs the latest version tensorflow and it works almost okay.
> Install with `pip install .` as said in the manual.

This is only solves the installation issue, but the package is useless without tensorflow 1.7. If requires the contrib module to guess the language but the module was deprecated.

**Comment by ViktorBarzin** [comment]
Yes this is just a temporary fix. I managed to install is this way and indeed many features to throw exceptions, but it seems that the basic functionality does work - its does recognize languages.

Can you suggest any other solution?

**Comment by rocbr** [comment]
Are you planning on adding support for tensorflow==2.0.0 and Python 3.7 ?
Tensorflow 2 Alpha was released and it is compatible with new versions of python.

https://www.tensorflow.org/install/pip#tensorflow-2.0-alpha-is-available

Thanks !

**Comment by yoeo** [comment]
Hello @AndydeCleyre , @Vikas2426, @ViktorBarzin , @rocbr 

The Tensorflow version have been updated to v2.2.0
You can test it with `pip install guesslang==2.0.0a1`

Thanks for the feedback.
