### ISSUE TITLE
If the Packagel can identity pure text?

### ISSUE THREAD

**Issue by LiuHao-THU** [yoeo/guesslang#15]
This Package is fantastic, however, it just provides with 20 classes without non-programming language(Pure Text). Can Further version add the function

**Comment by yoeo** [comment]
Hi @LiuHao-THU ,

I think that a "Pure Text" class would be too broad to fit in the current model, as pure text can be written in any language with any alphabet and contain any type of characters.

However, to reduce the chances of misclassifying pure text I added a check on the prediction probabilities.

That said, some text files may still be categorized as Markdown (as Markdown is a text formatting language) and Guesslang may have issues classifying some short code snippets, as stated in the documentation.

Thank you for the feedback.
