### ISSUE TITLE
Request: Detection support for additional syntaxes: json, kotlin, nginx, toml, xml, yaml

### ISSUE THREAD

**Issue by AndydeCleyre** [yoeo/guesslang#19]
Thanks so much for reviving your work!

I wasn't sure if you'd prefer a separate issue for each language here, just let me know.

Otherwise:

- [x] json
- [x] kotlin
- [ ] nginx
- [x] toml
- [x] xml
- [x] yaml

**Comment by yoeo** [comment]
Hi @AndydeCleyre ,

Thank you for the support :slightly_smiling_face: 

I'll check if I have enough sample files to add some of the listed languages.

**Comment by yoeo** [comment]
Hello @AndydeCleyre,

Happy to announce that Guesslang now supports json, kotlin, toml, xml, yaml and 19 other new languages.
https://github.com/yoeo/guesslang/pull/33

I couldn't add nginx because I didn't find enough example files.

**Comment by AndydeCleyre** [comment]
Amazing, thank you! It's working great.
