### ISSUE TITLE
[False Positive] Json file detected as SQL

### ISSUE THREAD

**Issue by emanuelb** [yoeo/guesslang#23]
Running `guesslang data-2.0.json` return `Programming language: SQL` 
while running `guesslang --probabilities data-2.0.json` return: (the other langs have 0%)
```
Language name       Probability
 SQL                  98.52%
 JavaScript            1.31%
 PHP                   0.16%
 Python                0.01%
```
The file is:
https://sources.debian.org/data/main/n/node-caniuse-db/1.0.30001048-1/fulldata-json/data-2.0.json

while running guesslang on file data-1.0.json from:
https://sources.debian.org/data/main/n/node-caniuse-db/1.0.30001048-1/fulldata-json/data-1.0.json
works somehow correctly by returning  `Programming language: JavaScript` & `JavaScript           100.00%` (as JSON not supported yet, but it's valid JavaScript)

**Comment by yoeo** [comment]
Hi @emanuelb 

Indeed, JSON is not supported yet. The current model was not trained with JSON files see:
https://github.com/yoeo/guesslang/blob/5537217d06cb1196359cc9366f14755039c4f905/guesslang/data/languages.json#L13

In consequence, even if Guesslang may sometimes correctly classify JSON as JavaScript, classification errors are highly expected here.

A proper support for JSON files is planned https://github.com/yoeo/guesslang/issues/19
I just need to find enough JSON example files to feed the model.

**Comment by yoeo** [comment]
Hello @emanuelb ,

Guesslang properly supports JSON now as well as 23 other languages that where not supported before https://github.com/yoeo/guesslang/pull/33 :slightly_smiling_face:
