### ISSUE TITLE
Detection support request for: VisualBasic, Pascal

### ISSUE THREAD

**Issue by Harniver** [yoeo/guesslang#24]
Thanks for your work! At @olimpiadi-informatica we are updating an online competitive programming contest platform to use guesslang. In order to fully support the languages taught in secondary schools, we would need additional support for:

- [x] VisualBasic
- [x] Pascal

**Comment by yoeo** [comment]
Hello @Harniver,

I'll check if I can support one or both languages in the next major version.

I just hope that I can find enough open source projects written in VisualBasic and Pascal to feed the machine learning model.
Feel free to share If you know where to find some.

Thank you.

**Comment by yoeo** [comment]
Hello @Harniver,

Both languages are now fully supported by Guesslang.
https://github.com/yoeo/guesslang/pull/33
