### ISSUE TITLE
Install Error:

### ISSUE THREAD

**Issue by JDJGInc** [yoeo/guesslang#28]
I currently have an error of:
[EnvCommandError]
Command ['/opt/virtualenvs/python3/bin/pip', 'install', '--no-deps', 'tensorflow==2.2.0'] errored with the following return code -9, and output: 
Collecting tensorflow==2.2.0
  Downloading tensorflow-2.2.0-cp38-cp38-manylinux2010_x86_64.whl (516.3 MB)

**Comment by yoeo** [comment]
Hi

The dependency issue is now fixed. You can install it with `pip install guesslang`
