### ISSUE TITLE
Question - Can I use it in my node web app?

### ISSUE THREAD

**Issue by max-programming** [yoeo/guesslang#35]
I really like this DL module and I don't know anything about machine learning. But I want to use this in [my app](https://easypastes.tk) to guess the language based on user input. 

Now, this app uses [Next.js](https://nextjs.org) and I wanted to ask that is there a way to use it in a nodejs based app?

**Comment by yoeo** [comment]
Hi @max-programming, your app looks very neat :+1: 

There is indeed a Javascript project that uses Guesslang model https://github.com/microsoft/vscode-languagedetection

I don't know NodeJS well, so I can't tell if the solutions used in this project will work on yours or not.
But do not hesitate to leave a message to the "vscode-languagedetection" maintainers if you have questions.

**Comment by max-programming** [comment]
Thanks for that @yoeo ! Will check out the Js project.

**Comment by yoeo** [comment]
I'm closing this issue for now, please re-open it if you have more questions.
