### ISSUE TITLE
The class "tf.contrib.learn.DNNLinearCombinedClassifier" has been deprecated in TensorFlow

### ISSUE THREAD

**Issue by Zidane-Han** [yoeo/guesslang#9]
Thanks for your package.

The api of the deep learning model used for this package has been deprecated, reported in the TensorFlow website.

https://www.tensorflow.org/api_docs/python/tf/contrib/learn/DNNLinearCombinedClassifier

**Comment by gameengineer** [comment]
Same thing here but getting a few more deprecated messages as well.

WARNING:tensorflow:From C:\Users\jonste\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
WARNING:tensorflow:From C:\Users\jonste\AppData\Local\Programs\Python\Python36\lib\site-packages\guesslang\guesser.py:60: calling DNNLinearCombinedClassifier.__init__ (from tensorflow.contrib.learn.python.learn.estimators.dnn_linear_combined) with fix_global_step_increment_bug=False is deprecated and will be removed after 2017-04-15.
Instructions for updating:
Please set fix_global_step_increment_bug=True and update training steps in your pipeline. See pydoc for details.
WARNING:tensorflow:From C:\Users\jonste\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn_linear_combined.py:676: multi_class_head (from tensorflow.contrib.learn.python.learn.estimators.head) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.contrib.estimator.*_head.
WARNING:tensorflow:From C:\Users\jonste\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py:1165: BaseEstimator.__init__ (from tensorflow.contrib.learn.python.learn.estimators.estimator) is deprecated and will be removed in a future version.
Instructions for updating:
Please replace uses of any Estimator from tf.contrib.learn with an Estimator from tf.estimator.*
WARNING:tensorflow:From C:\Users\jonste\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py:427: RunConfig.__init__ (from tensorflow.contrib.learn.python.learn.estimators.run_config) is deprecated and will be removed in a future version.
Instructions for updating:
When switching to tf.estimator.Estimator, use tf.estimator.RunConfig instead.
WARNING:tensorflow:From C:\Users\jonste\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\head.py:678: ModelFnOps.__new__ (from tensorflow.contrib.learn.python.learn.estimators.model_fn) is deprecated and will be removed in a future version.
Instructions for updating:
When switching to tf.estimator.Estimator, use tf.estimator.EstimatorSpec. You can use the `estimator_spec` method to create an equivalent one.
2018-11-13 10:56:53.542410: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2

It still seems to work when tested on C# files, so is there a way to quiet the warnings?

**Comment by gameengineer** [comment]
Ok so I found out you can change tensorflow logging level from inside our own .py files.

import tensorflow as tf
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
tf.logging.set_verbosity(tf.logging.FATAL)

That quieted all messages from tensorflow, except for the fatal ones of course.

**Comment by yoeo** [comment]
Hello @gameengineer 

That's a nice workaround. Thanks for sharing.

**Comment by gameengineer** [comment]
No problem! I really appreciate your work on this library its exactly what we needed. We need to detect source code files and third party libraries coming into our server. We have a more secure way to transfer these types of files at my company but sometimes they get through our less secure way.

**Comment by yoeo** [comment]
@Zidane-Han 

I've (finally) pushed an updated version of Guesslang that uses the latest Tensorflow API v2.2.0
You can test it with `pip install guesslang==2.0.0a1`

Thanks you.
